### ISSUE TITLE
Stuff to add

### ISSUE THREAD

**Issue by haato3o** [Haato3o/Heeto-Bot#1]
## Todo list
- [ ] Add server customization commands;
- [ ] Add more fun commands;
- [ ] Add inventory and shop;
